= Overview

This module provides interop with the https://github.com/functional-streams-for-scala/fs2[FS2] library.


== Getting Started

This module requires fs2, fs-reactive-streams on the classpath.

[source, scala]
....
val fs2Version = ??? // any recent one should work
libraryDependencies ++= Seq(
    "co.fs2" %% "fs2-core" % fs2Version,
    "co.fs2" %% "fs2-reactive-streams" % fs2Version,
    "be.wegenenverkeer" %% "rxhttp-fs2" % "2.0-RC1")
....

This will pull the `be.wegenenverkeer.rxhttpClient` package in as a transitive dependency.

== API

This module provides a Streaming API `FSHttpApi`:

[source, scala]
----
include::src/main/scala/be/wegenenverkeer/rxhttp/fs2/Fs2HttpApi.scala[lines=13..29]
----

After importing `fs2.Implicits._` a RxJavaHttpClient can be converted into an implementation
of this trait.

[source, scala]
----
val client : RxJavaHttpClient = ???
include::src/test/scala/Fs2InteropSpecification.scala[lines=24..26,indent=0]
----

== Usage

Here is an example that gets the response elements (chunks) in a `fs2.Stream[IO, String]`. Obviously,
the request will only fire when the effect is run.

[source, scala]
----
val client : RxJavaHttpClient = ???
include::src/test/scala/Fs2InteropSpecification.scala[lines=21..25, indent=0]
----

We can also return the complete response as a single value wrapped in an `IO`.
[source, scala]
----
include::src/test/scala/Fs2InteropSpecification.scala[lines=46, indent=0]
//resp : IO[String]
----



